version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Upgrade(prod):"
      prefix-development: "Upgrade(dev):"
    reviewers:
      - "evelynhathaway"
    assignees:
      - "evelynhathaway"
